### ISSUE TITLE
How to use in version 5.0.1 newIndex, oldIndex of orderUpdateEntities that were passed as parameters of onReorder

### ISSUE THREAD

**Issue by JangInho** [karvulf/flutter-reorderable-grid-view#112]
How to use in version 5.0.1 newIndex, oldIndex of orderUpdateEntities that were passed as parameters of onReorder

**Comment by karvulf** [comment]
Hello @JangInho 

Since the update I don't pass any indices. Instead you get a function which will do the reorder for you. 
This is how it works:
```dart
        onReorder: (ReorderedListFunction reorderedListFunction) {
          setState(() {
            _fruits = reorderedListFunction(_fruits) as List<String>;
          });
        },
```

In this example, you add your list which will be reordered to `reorderedListFunction` and cast the result as the type of your list. After that you update the state with the updated list.
Did it work for you?

**Comment by karvulf** [comment]
Closing this one because of no answer
